version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "angularjs",
    "angular"
  ]
  environment = [
    "nodejs",
    "jquery"
  ]